# MAPPING for logitech extreme 3d pro
uint8 AXIS_ROTATE = 2
uint8 AXIS_SLIDER = 3
uint8 AXIS_RIGHT = 0
uint8 AXIS_DOWN = 1
uint8 AXIS_HAT_RIGHT = 4
uint8 AXIS_HAT_DOWN = 5

uint8 BTN_TRIGGER = 0
uint8 BTN_ENABLER = 1
uint8 BTN_3 = 2
uint8 BTN_4 = 3
uint8 BTN_5 = 4
uint8 BTN_6 = 5
uint8 BTN_7 = 6
uint8 BTN_8 = 7
uint8 BTN_9 = 8
uint8 BTN_10 = 9
uint8 BTN_11 = 10
uint8 BTN_12 = 11



# sensor_msgs/Joy joy
joystick_interface/Joystick joy